# Generated by Django 3.1 on 2020-09-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnoffValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronoff', models.IntegerField()),
                ('yonoff', models.IntegerField()),
                ('bonoff', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ValueOfSpliteData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rvolt', models.IntegerField()),
                ('yvolt', models.IntegerField()),
                ('bvolt', models.IntegerField()),
                ('rcurrent', models.FloatField(max_length=999)),
                ('ycurrent', models.FloatField(max_length=999)),
                ('bcurrent', models.FloatField(max_length=999)),
                ('battery', models.IntegerField()),
            ],
        ),
    ]
