# Generated by Django 3.1 on 2020-11-01 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDevice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.IntegerField()),
                ('adress', models.IntegerField()),
                ('rmax', models.IntegerField()),
                ('rmin', models.FloatField(max_length=999)),
                ('ymax', models.FloatField(max_length=999)),
                ('ymin', models.FloatField(max_length=999)),
                ('bmax', models.IntegerField()),
                ('bmin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OnoffValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronoff', models.IntegerField()),
                ('yonoff', models.IntegerField()),
                ('bonoff', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ValueOfSpliteData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rvolt', models.IntegerField()),
                ('yvolt', models.IntegerField()),
                ('bvolt', models.IntegerField()),
                ('rcurrent', models.FloatField(max_length=999)),
                ('ycurrent', models.FloatField(max_length=999)),
                ('bcurrent', models.FloatField(max_length=999)),
                ('battery', models.IntegerField()),
                ('splitusername', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usersplit_values', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
