# Generated by Django 3.1 on 2020-11-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_adddevice_deviceuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddevice',
            name='adress',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='adddevice',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adddevice',
            name='rmin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='adddevice',
            name='ymax',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='adddevice',
            name='ymin',
            field=models.IntegerField(),
        ),
    ]
