# Generated by Django 3.1 on 2020-11-01 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20201101_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='valueofsplitedata',
            name='rybeuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ryb', to=settings.AUTH_USER_MODEL),
        ),
    ]
